# Tarea 15

Fecha de entrega: 17/Octubre/2017

Por _Diana López Angeles_

-----

# Librerias

__Ejercicio 1:__ Crear la libreria herramientas dentro de su carpeta de tareas, en su repositorio. Dentro deberán poner los métodos de Newton que construyeron, los métodos de integración, Euler independiente de dimensión (implícito y explícito)y Runge-Kutta independiente de dimensión. Recuerden que las rutinas deben funcionar solo con sus argumentos, no debe haber variables globales, todo lo que necesite la función para trabajar debe ser un argumento o una variable definida internamente.
* Las rutinas tienen que llevar su documentación.
* Crearán el notebook de la __tarea 15 (para el Martes 17)__ y en el llamarán a su libreria con el comando `import`.
* Deberán demostrar que sus rutinas funcionan bien, no se necesitan tests extensos, basta con que muestren que si _corren_ las rutinas.

In [1]:
__precompile__()

module herramientas

#Cargamos nuestros programas de la tarea 4:
export metodo_newton_arbitrario
function metodo_newton_arbitrario(f,df,x0,t)
    x = x0
    for i in 1:100                             
        x=x-(f(x)/df(x))                       
    end
return x
end;

export metodo_newton_intervalo
function metodo_newton_intervalo(f,df,intervalo)    
    list=zeros(length(intervalo))                   
    x = 0                                           
    for i in 1:length(intervalo)                    
        x = intervalo[i]                            
        for n in 1:200                              
            x = x-(f(x)/df(x))                      
            end                                     
    list[i]=x;                                      
    end
    list                                            
end;

export metodo_newton_epsilon
function metodo_newton_epsilon(f,df,intervalo)          
    t = []                                          
    epsilon = 10.0^-8                               
    list = metodo_newton_intervalo(f,df,intervalo)  
    push!(t,list[1])                                
    for i in 1:length(t)                            
        for n in 1:length(list)                     
            if abs(t[i]-list[n]) > epsilon          
                push!(t,list[n])                    
                end                               
        end
        return t                                            
    end
end

#Cargamos los programas de la tarea 5: Metodos de integracion
export sumas_Riemann
function sumas_Riemann(f,a,b,subintervalos)         
    N = subintervalos                                 
    A = a
    B = b
    datos = []                                      
    suma = 0                                          
    area_bajo_la_curva = 0
    for i in 1:N                                       
        b = ((B-A)/N)*(i) - A                          
        a = A + ((B-A)/N)*(i-1)
        area_bajo_la_curva = (b-a)*(f((b+a)/2))        
        push!(datos,area_bajo_la_curva)              
    end
    suma = sum(datos,1:N)                             
return suma
end;

export metodo_trapecio
function metodo_trapecio(f,a,b,subintervalos)            
    N = subintervalos                                  
    A = a
    B = b
    datos = []                                         
    suma = 0                                            
    area_bajo_la_curva = 0

    for i in 1:N
        b = ((B-A)/N)*(i) - A
        a = A + ((B-A)/N)*(i-1)
        area_bajo_la_curva = (b-a)*((f(b)+f(a))/2) 
        push!(datos,area_bajo_la_curva)
    end
    suma = sum(datos,1:N)
return suma
end;

#Cargamos los programas de la tarea 7:
export metodo_simpson
function metodo_simpson(f,a,b,subintervalos)           
    N = subintervalos                                  
    A = a
    B = b
    datos = []                                         
    suma = 0                                           
    area_bajo_la_curva = 0

    for i in 1:N
        b = ((B-A)/N)*(i) - A
        a = A + ((B-A)/N)*(i-1)
        area_bajo_la_curva = (b-a)/6*((f(a)+4f((a+b)/2))+f(b))
        push!(datos,area_bajo_la_curva)
    end
    suma = sum(datos,1:N)
return suma
end;

#Cargamos programas de la tarea 8:

export derivada_numerica
function derivada_numerica(f,x,h)
    df_ = (f(h+x)-f(x))/h 
    return df_ 
end;

#Cargamos programas de la tarea 11:

export metodo_euler
function metodo_euler(f,x0,t0,tf,h) 
    n=round((tf-t0)/h)+1                 
    listt=linspace(t0,tf,n)             
    listx=zeros(n)         
    listx[1]=x0             
    for i in 1:length(listx)-1   
        listx[i+1]=listx[i]+h*f(listx[i],listt[i])
    end
    return listt, listx
end;

export metodo_euler_dimensiones
function metodo_euler_dimensiones(f,list,x0)
     x = x0
     h = list[2]-list[1]
     listx=[]
     push!(listx,x)
     for i in 2:length(list)
        t = i*h
        x = x + f(x,t)*h
        push!(listx,x) 
     end
     return listx
    end;

#Cargamos programas de la tarea 12:
export euler_implicito
function euler_implicito(f,df,x0,t0,tf,h)
    n=round((tf-t0)/h)+1                 
    listt=linspace(t0,tf,n)
    listx = zeros(length(listt))
    x = x0 
    listx[1] = x0
    for i in 2:length(listt)
        g(x) = x - listx[i-1] - h*f(x,listt[i])
        dg(x) = 1 - h*df(x,listt[i])
        x = metodo_newton_arbitrario(g,dg,listx[i-1],listt[i])
        listx[i] = x
    end
    return (listt,listx)
end;

export euler_punto_medio
function euler_punto_medio(f,x0,t0,tf,h)
    n=round((tf-t0)/h)+1                 
    listt=linspace(t0,tf,n)             
    listx=zeros(n)
    listx[1]=x0                              
    for i in 1:length(listx)-1               
        listx[i+1]=listx[i]+h*f((listx[i]+(h/2)f(listx[i],listt[i])),listt[i+1])
    end
    return listt, listx
end;

export runge_kutta_4
function runge_kutta_4(f,x0,t0,tf,h)
    n=round((tf-t0)/h)+1               
    listt=linspace(t0,tf,n) 
    listx=zeros(n)  
    listx[1] = x0 
    for i in 1:length(listx)-1
        k1 = f(listx[i], listt[i])
        k2 = f(listx[i] + h*(k1)/2, listt[i+1])
        k3 = f(listx[i] + h*(k2)/2, listt[i+1])
        k4 = f(listx[i] + h*(k3), listt[i],)
        listx[i+1] = listx[i] + h/6*(k1 + 2*(k2) + 2*(k3) + k4)
    end
    return listt,listx
end;

export runge_kutta_dimensiones
function runge_kutta_dimensiones(f,list,x0)
     x = x0
     h = list[2]-list[1]
     listx=[]
     push!(listx,x)
     for i in 2:length(list)
        t = i*h
        k1 = f(x,t);
        k2 = f(x+(h/2)*k1,t+(h/2));
        k3 = f(x+(h/2)*k2, t+(h/2));
        k4 = f(x+h*k3, t+h);
        x = x+(h/6)*(k1+2*k2+2*k3+k4);
        push!(listx,x) 
     end
     return listx
end;
end

herramientas

##### Metodo de Newton Arbitrario:

In [2]:
import herramientas

In [3]:
herramientas.metodo_newton_arbitrario(x->x^3-x^2-x-1,x->3x^2-2x-1,45,1)

1.8392867552141612

##### Metodo de Newton Intervalo:

In [4]:
herramientas.metodo_newton_intervalo(x->x^3-x^2-x-1,x->3x^2-2x-1,linspace(0,10,3))

3-element Array{Float64,1}:
 1.83929
 1.83929
 1.83929

##### Metodo de Newton Epsilon:

In [5]:
herramientas.metodo_newton_epsilon(x->x^3-x^2-x-1,x->3x^2-2x-1,linspace(0,19,5))

1-element Array{Any,1}:
 1.83929

##### Sumas de Riemann:

In [6]:
herramientas.sumas_Riemann(x->x^3,0,1,1000)

1-element Array{Float64,1}:
 0.25

##### Metodo del trapecio:

In [7]:
herramientas.metodo_trapecio(x->x^3,0,1,1000)

1-element Array{Float64,1}:
 0.25

##### Metodo de Simpson:

In [8]:
herramientas.metodo_simpson(x->x^3,0,1,1000)

1-element Array{Float64,1}:
 0.25

##### Derivada númerica:

In [9]:
herramientas.derivada_numerica(x->x^3,1,100)

10303.0

##### Metodo de Euler:

In [10]:
herramientas.metodo_euler((x,t)->-(2.5)*x,1,0,8,0.5)

(0.0:0.5:8.0, [1.0, -0.25, 0.0625, -0.015625, 0.00390625, -0.000976563, 0.000244141, -6.10352e-5, 1.52588e-5, -3.8147e-6, 9.53674e-7, -2.38419e-7, 5.96046e-8, -1.49012e-8, 3.72529e-9, -9.31323e-10, 2.32831e-10])

##### Metodo de Euler varias dimensiones:

In [11]:
herramientas.metodo_euler_dimensiones((x,t)->[x[2], -1.0*x[1]],0:0.01:10,[0,2])

1001-element Array{Any,1}:
 [0, 2]               
 [0.02, 2.0]          
 [0.04, 1.9998]       
 [0.059998, 1.9994]   
 [0.079992, 1.9988]   
 [0.09998, 1.998]     
 [0.11996, 1.997]     
 [0.13993, 1.9958]    
 [0.159888, 1.9944]   
 [0.179832, 1.9928]   
 [0.19976, 1.991]     
 [0.21967, 1.98901]   
 [0.23956, 1.98681]   
 ⋮                    
 [-0.942105, -1.87836]
 [-0.960889, -1.86894]
 [-0.979578, -1.85933]
 [-0.998171, -1.84954]
 [-1.01667, -1.83955] 
 [-1.03506, -1.82939] 
 [-1.05336, -1.81904] 
 [-1.07155, -1.8085]  
 [-1.08963, -1.79779] 
 [-1.10761, -1.78689] 
 [-1.12548, -1.77581] 
 [-1.14324, -1.76456] 

##### Euler implicito:

In [12]:
herramientas.euler_implicito((x,t)->-2.5x,(x,t)->-2.5,1,0,8,.01)

(0.0:0.01:8.0, [1.0, 0.97561, 0.951814, 0.928599, 0.905951, 0.883854, 0.862297, 0.841265, 0.820747, 0.800728  …  3.29172e-9, 3.21143e-9, 3.1331e-9, 3.05669e-9, 2.98213e-9, 2.9094e-9, 2.83844e-9, 2.76921e-9, 2.70167e-9, 2.63577e-9])

##### Euler punto medio:

In [13]:
herramientas.euler_punto_medio((x,t)->-2.5x,1,0,8,0.01)

(0.0:0.01:8.0, [1.0, 0.975313, 0.951234, 0.927751, 0.904847, 0.882509, 0.860722, 0.839473, 0.818748, 0.798535  …  2.58665e-9, 2.52279e-9, 2.46051e-9, 2.39977e-9, 2.34053e-9, 2.28274e-9, 2.22639e-9, 2.17142e-9, 2.11782e-9, 2.06553e-9])

##### Runge Kutta 4

In [14]:
herramientas.runge_kutta_4((x,t)->-2.5x,1,0,8,.01)

(0.0:0.01:8.0, [1.0, 0.97531, 0.951229, 0.927743, 0.904837, 0.882497, 0.860708, 0.839457, 0.818731, 0.798516  …  2.58123e-9, 2.5175e-9, 2.45534e-9, 2.39472e-9, 2.33559e-9, 2.27793e-9, 2.22168e-9, 2.16683e-9, 2.11333e-9, 2.06115e-9])

##### Runge Kutta orden 4, varias dimensiones:

In [15]:
herramientas.runge_kutta_dimensiones((x,t)->[x[2], -1.0*x[1]-x[2]],0:0.01:10,[1,0])

1001-element Array{Any,1}:
 [1, 0]                    
 [0.99995, -0.00995]       
 [0.999801, -0.0198]       
 [0.999554, -0.02955]      
 [0.999211, -0.0392001]    
 [0.998771, -0.0487503]    
 [0.998236, -0.0582005]    
 [0.997607, -0.067551]     
 [0.996885, -0.0768017]    
 [0.996071, -0.0859527]    
 [0.995167, -0.0950041]    
 [0.994172, -0.103956]     
 [0.993088, -0.112808]     
 ⋮                         
 [-0.00153155, -0.00622848]
 [-0.00159345, -0.00615096]
 [-0.00165457, -0.0060736] 
 [-0.00171492, -0.0059964] 
 [-0.0017745, -0.00591937] 
 [-0.00183331, -0.00584252]
 [-0.00189135, -0.00576586]
 [-0.00194863, -0.00568938]
 [-0.00200514, -0.0056131] 
 [-0.00206089, -0.00553702]
 [-0.00211588, -0.00546114]
 [-0.00217012, -0.00538548]